export default [
  {
    name: "10-P 3",
    studentNames: [
      "Brendon",
      "Sophie",
      "Sophie",
      "Frieda",
      "Dylan",
      "Elliot",
      "Connie",
      "laylah",
      "Charlie",
      "Katy",
      "Adina",
      "Ruby",
      "Phoebe",
      "Ewan",
      "Carolina",
      "Olivia",
      "Phoebe",
      "Violet",
      "Mayah",
      "Tomas",
      "George",
      "Toby",
      "Lewis",
      "Charlie",
    ],
  },
  {
    name: "9Q-P",
    studentNames: [
      "Ava",
      "Lily",
      "Herbie",
      "Finley",
      "Gregory",
      "Imogen",
      "Ciaran",
      "Olivia",
      "Mutumwa",
      "Harriet",
      "Chi Hang",
      "Samuel",
      "Harry",
      "Morgan",
      "Joseph",
      "Jason",
      "Elizabeth",
      "Torrin",
      "Thomas",
      "Cole",
      "Bailey",
      "Noah",
      "Charlie",
    ],
  },
  {
    name: "11-P 1",
    studentNames: [
      "Cara",
      "Tabitha",
      "Melissa",
      "Erin",
      "Qhyais",
      "Morgan",
      "Izzy",
      "William",
      "Max",
      "Ellisha",
      "Frosty",
      "Teagan",
      "Ayla",
      "Sibusiso",
      "angharad",
      "Ella",
      "William",
      "Sophie",
      "Joseph",
      "Esther",
      "Isaac",
    ],
  },
  {
    name: "10B-P",
    studentNames: [
      "Nathaniel",
      "Lulu",
      "Cole",
      "Dan",
      "Leo",
      "Kirsty",
      "Isla",
      "Lois",
      "Aydin",
      "Sam",
      "Jake",
      "Henry",
      "Anna ",
      "Evie",
      "Amelia",
      "Sophia",
      "Leo",
      "James",
      "Ngo Tin",
      "Tin Lam",
      "Harriet",
      "Ella",
      "Charmaine",
      "Grace",
      "Charlie",
      "Oliver",
      "Esther",
    ],
  },
  {
    name: "6E-P",
    studentNames: [
      "Milagros",
      "Kosuke",
      "Sinead",
      "Zhihang",
      "Xinyan",
      "Edan",
      "Sam",
      "Adrian",
      "Max",
      "teo",
      "Khayaam",
      "Lewis",
      "Cyrus",
      "Cymbal",
      "Freddie",
      "Rio",
      "Brandon",
      "Dominic",
      "Maryan",
    ],
  },
  {
    name: "10-AT-KC",
    studentNames: [
      "Clara",
      "Javier",
      "Maxi",
      "Connie",
      "laylah",
      "Leo",
      "Seb",
      "Sam",
      "Oliver",
      "George",
      "Harriet",
      "Ella",
      "Christy",
      "Sofiia",
    ],
  },
  {
    name: "10T-R",
    studentNames: [
      "Clara",
      "Sophie",
      "Connie",
      "Katy",
      "Kirsty",
      "Isla",
      "Lulu",
      "Lois",
      "Anna ",
      "Phoebe",
      "Evie",
      "Amelia",
      "Amalia- Dorothea",
      "Candela",
      "Violet",
      "Katie",
      "Ella",
      "Christy",
      "Pippa",
      "Sofiia",
      "Imogen",
    ],
  },
  {
    name: "13B-P",
    studentNames: [
      "Cyrus",
      "Adrian",
      "Sam",
      "Khayaam",
      "Zhihang",
      "Dominic",
      "Sinead",
    ],
  },
  {
    name: "12A-P",
    studentNames: [
      "Takeshi",
      "Zhuo",
      "Freddie",
      "Adam",
      "Harry",
      "Kai Tik",
      "Ash",
      "Naz",
      "Cyrus",
      "Alexander",
      "George",
      "Hinson",
      "Edward",
    ],
  },
  {
    name: "11-P",
    studentNames: [
      "Cara",
      "Ayla",
      "Ella",
      "angharad",
      "Sophie",
      "Teagan",
      "Erin",
      "Isaac",
      "William",
      "Joseph",
      "Ellisha",
      "Tabitha",
      "William",
      "Frosty",
      "Qhyais",
      "Morgan",
      "Izzy",
      "Sibusiso",
      "Max",
      "Melissa",
      "Esther",
    ],
  },
];
